### ISSUE TITLE
Swift Dagger has name set as "Silver Dagger"

### ISSUE THREAD

**Issue by PlatypusKing** [telemmo/telemmo#71]
change the "name: field of swift dagger to Silver Dagger for clarity (so there aren't two silver daggers)

 {
    id: 'swift_dagger',
    name: 'Silver Dagger',
    description: 'It\'s really light.',
    type: 'weapon',
    tier: 2,
    bonus: {
      str: 3,
      ref: 5,
    },
    fire: (attacker, defender, rolls) => ({
      noCast: rolls.aAim < 17,
      defender: {
        hp: - ( 4 + attacker.level/10),
      },
      log: {
        type: 'damage',
        value: 4 + attacker.level/10,

**Comment by Croebh** [comment]
Should be fixed with this [pull request](https://github.com/telemmo/telemmo/pull/70)

**Comment by Croebh** [comment]
#70

**Comment by MarcoWorms** [comment]
Thanks guys! Awesome :D
