### ISSUE TITLE
Fix hp showing less than 0

### ISSUE THREAD

**Issue by atillagallio** [telemmo/telemmo#85]

**Comment by MarcoWorms** [comment]
I did this on purpose but i'm totally ok with changing it :D, I think people liked overkills.

**Comment by KurzedMetal** [comment]
I think this is fine too. +1 for showing overkill damage.
The -0 HP is kinda weird tho and a totally different issue.

**Comment by MarcoWorms** [comment]
Closing this but if someone want's it to change just send an PR (or open up another issue) :)
