### ISSUE TITLE
Add /wiki command

### ISSUE THREAD

**Issue by Croebh** [telemmo/telemmo#87]
With possibility of /wiki_zones, etc

**Comment by KurzedMetal** [comment]
What is this "/wiki" command supposed to do?

**Comment by MarcoWorms** [comment]
IMO it could link some stuff to the wiki. I don't think it's wise to put wiki text inside the game because it's one more thing to mantain in the code base and i'd say it's not worth it, we could just link to the page :)

**Comment by derekstavis** [comment]
Done in #114
